name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-staging:
    name: 🚀 Staging
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      # SAMPLE 2: Mapping to Env Var (Recommended)
      # Safer for scripts and complex variables
      - name: Method 2 Mapped Variable
        env:
          TARGET_URL: ${{ vars.STAGING_URL }}
        run: |
          echo "Using Method 2 (Mapped)"
          curl -f "$TARGET_URL"

  approve-production:
    name: 🔐 Await Approval
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Approval granted"

  deploy-production:
    name: 🎉 Production
    if: github.ref_type == 'tag'
    needs: approve-production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Production Curl
        run: curl -f "${{ vars.PROD_URL }}"
